"""Fictional domain definitions and deterministic evidence generation."""

from __future__ import annotations

from dataclasses import asdict, dataclass
import math
import random
from typing import Iterable

VARIABLES = ("m", "r", "q", "s")


@dataclass(frozen=True)
class Law:
    """A multiplicative power law over the four fictional variables."""

    name: str
    constant: float
    exponents: tuple[float, float, float, float]

    def evaluate(self, values: Iterable[float]) -> float:
        values_tuple = tuple(values)
        if len(values_tuple) != len(VARIABLES):
            raise ValueError(f"Expected {len(VARIABLES)} inputs, got {len(values_tuple)}")
        if self.constant <= 0:
            raise ValueError("The multiplicative constant must be positive")

        result = self.constant
        for value, exponent in zip(values_tuple, self.exponents, strict=True):
            if value <= 0:
                raise ValueError("Power-law inputs must be positive")
            result *= value**exponent
        return result


LAW_A = Law(
    name="L_A",
    constant=3.0,
    exponents=(1.0, 2.0, -1.0, 0.0),
)

LAW_B = Law(
    name="L_B",
    constant=3.0,
    exponents=(1.0, 1.0, -2.0, 0.0),
)


@dataclass(frozen=True)
class Observation:
    """One row of fictional measurements."""

    m: float
    r: float
    q: float
    s: float
    tau: float

    @property
    def inputs(self) -> tuple[float, float, float, float]:
        return (self.m, self.r, self.q, self.s)

    def to_dict(self) -> dict[str, float]:
        return asdict(self)


@dataclass(frozen=True)
class EvidenceDataset:
    """A reproducible collection of observations generated by one law."""

    seed: int
    law_name: str
    design: str
    noise_sigma: float
    observations: tuple[Observation, ...]

    def to_dict(self) -> dict[str, object]:
        return {
            "seed": self.seed,
            "law_name": self.law_name,
            "design": self.design,
            "noise_sigma": self.noise_sigma,
            "observations": [row.to_dict() for row in self.observations],
        }


def _sample_log_uniform(rng: random.Random, low: float, high: float) -> float:
    if low <= 0 or high <= low:
        raise ValueError("Log-uniform bounds must satisfy 0 < low < high")
    return math.exp(rng.uniform(math.log(low), math.log(high)))


def generate_evidence(
    *,
    law: Law = LAW_A,
    n: int = 40,
    sigma: float = 0.0,
    seed: int = 1729,
    low: float = 0.5,
    high: float = 5.0,
) -> EvidenceDataset:
    """Generate seeded evidence with multiplicative log-normal noise."""

    if n <= 0:
        raise ValueError("n must be positive")
    if sigma < 0:
        raise ValueError("sigma must be non-negative")

    rng = random.Random(seed)
    rows: list[Observation] = []

    for _ in range(n):
        inputs = tuple(_sample_log_uniform(rng, low, high) for _ in VARIABLES)
        clean_tau = law.evaluate(inputs)
        epsilon = rng.gauss(0.0, sigma) if sigma else 0.0
        tau = clean_tau * math.exp(epsilon)
        rows.append(Observation(*inputs, tau))

    return EvidenceDataset(
        seed=seed,
        law_name=law.name,
        design="random",
        noise_sigma=sigma,
        observations=tuple(rows),
    )


def generate_isolating_evidence(
    *,
    law: Law = LAW_A,
    sigma: float = 0.0,
    seed: int = 1729,
    baseline: float = 1.0,
    low_sweep_bounds: tuple[float, float] = (0.2, 0.8),
    high_sweep_bounds: tuple[float, float] = (1.25, 5.0),
) -> EvidenceDataset:
    """Generate controlled sweeps that isolate one exponent at a time.

    The dataset contains one all-baseline observation. Every other row changes exactly
    one input while holding the other three at the baseline. Row order is shuffled by
    the seed so repeated gate cases do not rely on a privileged presentation order.
    """

    if sigma < 0:
        raise ValueError("sigma must be non-negative")
    if baseline <= 0:
        raise ValueError("baseline must be positive")
    low_min, low_max = low_sweep_bounds
    high_min, high_max = high_sweep_bounds
    if not (0 < low_min < low_max < baseline):
        raise ValueError("low sweep bounds must satisfy 0 < min < max < baseline")
    if not (baseline < high_min < high_max):
        raise ValueError("high sweep bounds must satisfy baseline < min < max")

    rng = random.Random(seed)
    input_rows: list[tuple[float, float, float, float]] = [
        (baseline,) * len(VARIABLES)
    ]
    for variable_index in range(len(VARIABLES)):
        sweep_values = (
            _sample_log_uniform(rng, low_min, low_max),
            _sample_log_uniform(rng, high_min, high_max),
        )
        for value in sweep_values:
            inputs = [baseline] * len(VARIABLES)
            inputs[variable_index] = value
            input_rows.append(tuple(inputs))

    rows: list[Observation] = []
    for inputs in input_rows:
        clean_tau = law.evaluate(inputs)
        epsilon = rng.gauss(0.0, sigma) if sigma else 0.0
        rows.append(Observation(*inputs, clean_tau * math.exp(epsilon)))

    rng.shuffle(rows)
    return EvidenceDataset(
        seed=seed,
        law_name=law.name,
        design="isolating",
        noise_sigma=sigma,
        observations=tuple(rows),
    )
