"""Build the reviewer-facing Jupyter notebook from readable cell sources."""

from __future__ import annotations

from pathlib import Path

import nbformat as nbf


ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK_PATH = ROOT / "notebooks" / "prior_evidence_demo.ipynb"


def build_notebook() -> nbf.NotebookNode:
    notebook = nbf.v4.new_notebook()
    notebook["metadata"] = {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "name": "python",
            "version": "3.11",
        },
    }

    cells: list[nbf.NotebookNode] = []

    cells.append(
        nbf.v4.new_markdown_cell(
            r"""# Prior knowledge versus new evidence

This notebook is the reviewer-facing demonstration for the first experimental block.

**Question:** if a fictional scientific law is stated as established background knowledge,
will Qwen3-8B still infer a conflicting law from clean numerical observations?

The notebook has two modes:

- **Cached mode (default):** loads the checked-in prompts and all 130 saved generation
  records. It requires no model download and reproduces the reported tables.
- **Live mode (optional):** runs one selected response through Qwen3-8B using MLX on
  Apple silicon.

The notebook imports the experiment implementation from `src/prior_evidence`; it does
not contain a separate copy of the scientific logic.

After cloning the repository, the complete cached demonstration runs with:

```bash
python -m pip install -e ".[notebook]"
jupyter lab notebooks/prior_evidence_demo.ipynb
```

No credentials, model weights, or external services are required in cached mode."""
        )
    )

    cells.append(
        nbf.v4.new_code_cell(
            """from pathlib import Path
import hashlib
import json
import math
import sys

from IPython.display import Markdown, display


def find_repo_root(start: Path) -> Path:
    candidates = (start.resolve(), *start.resolve().parents)
    for candidate in candidates:
        if (candidate / "pyproject.toml").exists() and (
            candidate / "src" / "prior_evidence"
        ).exists():
            return candidate
    raise RuntimeError("Could not locate the repository root.")


ROOT = find_repo_root(Path.cwd())
SRC = ROOT / "src"
EXPERIMENT_DIR = ROOT / "experiments" / "01_in_context_vs_base"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

# Reviewer controls. Cached mode works without a model download.
MODE = "cached"  # "cached" or "live_mlx"
DATASET_SEED = 2000
TARGET_LAW = "L_B"  # "L_A" or "L_B"
PRIOR_ARM = "bare"  # "none", "guided", or "bare"

# Optionally paste a response from any other model and score it with this benchmark.
# When set to a non-empty string, this takes precedence over MODE.
PASTED_RESPONSE = None

if MODE not in {"cached", "live_mlx"}:
    raise ValueError("MODE must be 'cached' or 'live_mlx'")
if TARGET_LAW not in {"L_A", "L_B"}:
    raise ValueError("TARGET_LAW must be 'L_A' or 'L_B'")
if PRIOR_ARM not in {"none", "guided", "bare"}:
    raise ValueError("PRIOR_ARM must be 'none', 'guided', or 'bare'")

print(f"Repository: {ROOT.name}")
print(
    f"Mode={MODE}, seed={DATASET_SEED}, target={TARGET_LAW}, "
    f"prior_arm={PRIOR_ARM}"
)"""
        )
    )

    cells.append(
        nbf.v4.new_markdown_cell(
            r"""## 1. Controlled fictional laws

The model is told that the quantities belong to a fictional neryx domain. The prior law is

$$
L_A:\qquad \tau = 3m^1r^2q^{-1}s^0,
$$

while the default conflicting observations are generated by

$$
L_B:\qquad \tau = 3m^1r^1q^{-2}s^0.
$$

Fictional names reduce direct lexical recall of a named real-world law. They do not remove
the model's general mathematical knowledge about ratios and power laws. Change
`TARGET_LAW` in the configuration cell to generate observations from either law."""
        )
    )

    cells.append(
        nbf.v4.new_code_cell(
            """from prior_evidence.domain import (
    LAW_A,
    LAW_B,
    VARIABLES,
    generate_evidence,
    generate_isolating_evidence,
)
from prior_evidence.metrics import exponent_l1_error, heldout_log_mse, law_matches
from prior_evidence.parsing import HypothesisParseError, parse_hypothesis
from prior_evidence.prompting import build_messages

LAW_BY_NAME = {"L_A": LAW_A, "L_B": LAW_B}
target_law = LAW_BY_NAME[TARGET_LAW]
dataset = generate_isolating_evidence(
    law=target_law,
    sigma=0.0,
    seed=DATASET_SEED,
)


def changed_variable(row) -> str:
    changed = [
        variable
        for variable, value in zip(VARIABLES, row.inputs, strict=True)
        if value != 1.0
    ]
    return changed[0] if changed else "baseline"


order = {"baseline": 0, "m": 1, "r": 2, "q": 3, "s": 4}
ordered_rows = sorted(
    dataset.observations,
    key=lambda row: (order[changed_variable(row)], row.inputs),
)

table = [
    "| sweep | m | r | q | s | tau |",
    "|---|---:|---:|---:|---:|---:|",
]
for row in ordered_rows:
    table.append(
        f"| {changed_variable(row)} | {row.m:.6g} | {row.r:.6g} | "
        f"{row.q:.6g} | {row.s:.6g} | {row.tau:.6g} |"
    )

display(Markdown("\\n".join(table)))"""
        )
    )

    cells.append(
        nbf.v4.new_markdown_cell(
            r"""Each non-baseline row changes exactly one variable. This makes an exponent directly
recoverable from a ratio:

$$
\frac{\tau_2}{\tau_1}
=
\left(\frac{x_2}{x_1}\right)^{\alpha_x},
\qquad
\alpha_x
=
\frac{\log(\tau_2/\tau_1)}{\log(x_2/x_1)}.
$$

The formula is shown here to explain the design. It is **not included in the model
prompt**."""
        )
    )

    cells.append(
        nbf.v4.new_code_cell(
            """baseline = next(
    row for row in dataset.observations if changed_variable(row) == "baseline"
)
q_row = next(
    row
    for row in dataset.observations
    if changed_variable(row) == "q" and row.q < 1
)
inferred_q_exponent = math.log(q_row.tau / baseline.tau) / math.log(
    q_row.q / baseline.q
)

display(
    Markdown(
        f"For the low-$q$ intervention, $q={q_row.q:.4f}$ and "
        f"$\\\\tau={q_row.tau:.4f}$. Relative to the baseline, this gives "
        f"$\\\\alpha_q={inferred_q_exponent:.6f}$. The configured target has "
        f"exact exponent ${target_law.exponents[2]:g}$."
    )
)"""
        )
    )

    cells.append(
        nbf.v4.new_markdown_cell(
            r"""## 2. Three prompt arms

All arms receive the same configured observations and the same hypothesis class. The
checked-in comparison uses seeds 2000 through 2009 with $L_B$ observations.

1. **No prior:** the model sees only the observations.
2. **Guided in-context prior:** $L_A$ is stated, followed by explicit guidance that the
   observations may confirm or contradict it.
3. **Bare in-context prior:** $L_A$ is stated as established background knowledge, with
   no warning that it may be wrong and no instruction to override it.

The bare arm addresses the concern that the guided wording itself encouraged rejection of
the prior. The configuration cell selects which arm will be loaded or run below."""
        )
    )

    cells.append(
        nbf.v4.new_code_cell(
            """ARM_CONFIG_TO_INTERNAL = {
    "none": "none",
    "guided": "in_context",
    "bare": "in_context_bare",
}
ARM_LABELS = {
    "none": "No prior",
    "in_context": "Guided in-context prior",
    "in_context_bare": "Bare in-context prior",
}
selected_internal_arm = ARM_CONFIG_TO_INTERNAL[PRIOR_ARM]
messages_by_arm = {
    arm: build_messages(dataset, prior_arm=arm)
    for arm in ARM_LABELS
}

for arm, label in ARM_LABELS.items():
    messages = messages_by_arm[arm]
    rendered = "\\n\\n".join(
        f"[{message['role'].upper()}]\\n{message['content']}" for message in messages
    )
    display(
        Markdown(
            f"<details><summary><strong>{label}: exact prompt</strong></summary>\\n\\n"
            f"```text\\n{rendered}\\n```\\n\\n</details>"
        )
    )

print(f"Selected arm: {ARM_LABELS[selected_internal_arm]}")"""
        )
    )

    cells.append(
        nbf.v4.new_code_cell(
            """guided_user = messages_by_arm["in_context"][1]["content"]
bare_user = messages_by_arm["in_context_bare"][1]["content"]

removed_guidance = (
    "Use this as prior knowledge when analyzing the new observations. The observations may\\n"
    "confirm or contradict the background law. Report the law best supported by the supplied\\n"
    "observations."
)

print("Guidance present in guided prompt:", removed_guidance in guided_user)
print("Guidance present in bare prompt:  ", removed_guidance in bare_user)"""
        )
    )

    cells.append(
        nbf.v4.new_markdown_cell(
            r"""## 3. Load and validate the checked-in experiment

The repository includes all raw generation records, rather than only a hand-written
summary:

- 100 feasibility generations;
- 10 no-prior $L_B$ generations;
- 10 guided-prior generations;
- 10 bare-prior generations.

First, verify that the checked-in artifacts match their SHA-256 manifest."""
        )
    )

    cells.append(
        nbf.v4.new_code_cell(
            """def verify_checksums(experiment_dir: Path) -> list[str]:
    verified = []
    manifest = experiment_dir / "SHA256SUMS"
    for line in manifest.read_text().splitlines():
        expected, relative_path = line.split(maxsplit=1)
        payload = (experiment_dir / relative_path).read_bytes()
        observed = hashlib.sha256(payload).hexdigest()
        if observed != expected:
            raise ValueError(f"Checksum mismatch: {relative_path}")
        verified.append(relative_path)
    return verified


verified = verify_checksums(EXPERIMENT_DIR)
print(f"Verified {len(verified)} checked-in experiment files.")"""
        )
    )

    cells.append(
        nbf.v4.new_code_cell(
            """def load_jsonl(path: Path) -> list[dict]:
    return [
        json.loads(line)
        for line in path.read_text().splitlines()
        if line.strip()
    ]


artifact_dir = EXPERIMENT_DIR / "artifacts"
records = {
    "feasibility": load_jsonl(artifact_dir / "feasibility_runs.jsonl"),
    "none": load_jsonl(artifact_dir / "no_prior_law_b_runs.jsonl"),
    "in_context": load_jsonl(artifact_dir / "in_context_guided_runs.jsonl"),
    "in_context_bare": load_jsonl(artifact_dir / "in_context_bare_runs.jsonl"),
}
experiment_summary = json.loads(
    (EXPERIMENT_DIR / "results" / "experiment_summary.json").read_text()
)

print({name: len(rows) for name, rows in records.items()})"""
        )
    )

    cells.append(
        nbf.v4.new_markdown_cell(
            r"""## 4. Try one configured case

The notebook now selects the response corresponding to the configuration at the top:

- in `cached` mode, it finds the matching checked-in Qwen trace;
- in `live_mlx` mode, it generates one new trace;
- when `PASTED_RESPONSE` is supplied, it scores that response instead.

Cached $L_B$ traces are available for seeds 2000–2009 in all three prompt arms."""
        )
    )

    cells.append(
        nbf.v4.new_code_cell(
            """selected_record = None
raw_response = None
response_source = None
response_truncated = None

if PASTED_RESPONSE:
    raw_response = PASTED_RESPONSE
    response_source = "pasted response"
elif MODE == "cached":
    if TARGET_LAW == "L_B":
        candidates = [
            row
            for row in records[selected_internal_arm]
            if row["dataset_seed"] == DATASET_SEED
        ]
        if candidates:
            selected_record = candidates[0]
            raw_response = selected_record["raw_response"]
            response_truncated = selected_record["truncated"]
            response_source = (
                f"cached {ARM_LABELS[selected_internal_arm]} trace, "
                f"seed {DATASET_SEED}"
            )
    if raw_response is None:
        display(
            Markdown(
                "**No cached response exists for this configuration.** "
                "Choose target `L_B` with a seed from 2000 through 2009, "
                "switch to `live_mlx`, or paste a response."
            )
        )
elif MODE == "live_mlx":
    from prior_evidence.backends import MLXBackend

    backend = MLXBackend(
        "mlx-community/Qwen3-8B-4bit",
        enable_thinking=True,
        top_p=0.95,
        top_k=20,
    )
    generation = backend.generate(
        messages_by_arm[selected_internal_arm],
        max_tokens=6144,
        temperature=0.6,
        seed=10_000_000 + DATASET_SEED,
    )
    raw_response = generation.text
    response_truncated = generation.finish_reason == "length" or (
        "<think>" in generation.text and "</think>" not in generation.text
    )
    response_source = "fresh MLX generation"

print(f"Response source: {response_source or 'none'}")"""
        )
    )

    cells.append(
        nbf.v4.new_code_cell(
            """def visible_answer(raw: str) -> str:
    return raw.rsplit("</think>", 1)[-1].strip()


if raw_response is not None:
    try:
        parsed = parse_hypothesis(raw_response)
        parse_error = None
    except HypothesisParseError as exc:
        parsed = None
        parse_error = str(exc)

    if parsed is not None:
        heldout = generate_evidence(
            law=target_law,
            n=200,
            sigma=0.0,
            seed=DATASET_SEED + 1_000_000,
        )
        score = {
            "matches_target": law_matches(parsed, target_law),
            "matches_L_A_prior": law_matches(parsed, LAW_A),
            "exponent_L1_error": exponent_l1_error(parsed, target_law),
            "heldout_log_MSE": heldout_log_mse(parsed, heldout),
            "truncated": response_truncated,
        }
    else:
        score = {
            "matches_target": False,
            "matches_L_A_prior": False,
            "exponent_L1_error": None,
            "heldout_log_MSE": None,
            "truncated": response_truncated,
        }

    display(
        Markdown(
            f"### Scored response: {response_source}\\n\\n"
            f"```json\\n{visible_answer(raw_response)}\\n```"
        )
    )
    print("Parsed hypothesis:", parsed.to_dict() if parsed is not None else None)
    print("Parse error:", parse_error)
    print(json.dumps(score, indent=2))
else:
    parsed = None
    score = None"""
        )
    )

    cells.append(
        nbf.v4.new_markdown_cell(
            r"""## 5. Feasibility gate

The prior comparison is meaningful only if the base model can infer a controlled power
law from evidence. The feasibility gate used 20 independently varied $L_A$ datasets and
five samples per dataset."""
        )
    )

    cells.append(
        nbf.v4.new_code_cell(
            """feasibility_runs = records["feasibility"]
feasibility_dataset_count = len(
    {row["dataset_seed"] for row in feasibility_runs}
)
feasibility = {
    "datasets": feasibility_dataset_count,
    "samples_per_dataset": len(feasibility_runs) // feasibility_dataset_count,
    "total_generations": len(feasibility_runs),
    "valid_exact_outputs": sum(
        not row["truncated"]
        and row["parse_error"] is None
        and row["law_match"]
        for row in feasibility_runs
    ),
    "completed_output_contract_failures": sum(
        not row["truncated"] and row["parse_error"] is not None
        for row in feasibility_runs
    ),
    "truncations_after_correct_derivation": sum(
        row["truncated"] for row in feasibility_runs
    ),
    "scientifically_wrong_parsed_outputs": sum(
        not row["truncated"]
        and row["parse_error"] is None
        and not row["law_match"]
        for row in feasibility_runs
    ),
}

# The summary is a cross-check, not the source of the displayed counts.
assert feasibility == experiment_summary["feasibility"]

feasibility_table = [
    "| quantity | count |",
    "|---|---:|",
    f"| Total generations | {feasibility['total_generations']} |",
    f"| Valid exact outputs | {feasibility['valid_exact_outputs']} |",
    f"| Completed output-contract failures after correct derivation | "
    f"{feasibility['completed_output_contract_failures']} |",
    f"| Truncations after correct derivation | "
    f"{feasibility['truncations_after_correct_derivation']} |",
    f"| Scientifically wrong parsed outputs | "
    f"{feasibility['scientifically_wrong_parsed_outputs']} |",
]
display(Markdown("\\n".join(feasibility_table)))"""
        )
    )

    cells.append(
        nbf.v4.new_markdown_cell(
            r"""The four non-valid generations were not alternative scientific hypotheses: two violated
the requested JSON contract after deriving the correct law, and two reached the token
limit after deriving the correct exponents. Parsed hypotheses had zero exponent error and
zero held-out prediction error."""
        )
    )

    cells.append(
        nbf.v4.new_markdown_cell(
            r"""## 6. Matched in-context comparison

The following mechanical counts are recomputed from the raw JSONL records for ten matched
$L_B$ datasets with seeds 2000–2009. The curated summary is used only as an assertion
that the recomputation agrees with the reported result."""
        )
    )

    cells.append(
        nbf.v4.new_code_cell(
            """def aggregate_arm(rows: list[dict]) -> dict[str, int]:
    parsed_rows = []
    for row in rows:
        try:
            hypothesis = parse_hypothesis(row["raw_response"])
        except HypothesisParseError:
            hypothesis = None
        parsed_rows.append((row, hypothesis))

    return {
        "total": len(rows),
        "valid_exact_L_B": sum(
            not row["truncated"]
            and hypothesis is not None
            and law_matches(hypothesis, LAW_B)
            for row, hypothesis in parsed_rows
        ),
        "parse_failures": sum(
            not row["truncated"] and hypothesis is None
            for row, hypothesis in parsed_rows
        ),
        "truncations": sum(row["truncated"] for row in rows),
        "L_A_outputs": sum(
            not row["truncated"]
            and hypothesis is not None
            and law_matches(hypothesis, LAW_A)
            for row, hypothesis in parsed_rows
        ),
    }


computed_comparison = {
    arm: aggregate_arm(records[arm])
    for arm in ("none", "in_context", "in_context_bare")
}
reported_comparison = experiment_summary["matched_conflict_comparison"]

assert computed_comparison["none"]["valid_exact_L_B"] == (
    reported_comparison["no_prior"]["valid_exact_l_b_outputs"]
)
assert computed_comparison["in_context"]["valid_exact_L_B"] == (
    reported_comparison["guided_in_context_l_a"]["valid_exact_l_b_outputs"]
)
assert computed_comparison["in_context_bare"]["valid_exact_L_B"] == (
    reported_comparison["bare_in_context_l_a"][
        "completed_valid_exact_l_b_outputs"
    ]
)
assert all(row["L_A_outputs"] == 0 for row in computed_comparison.values())

result_table = [
    "| arm | exact valid L_B | parse failures | truncations | L_A outputs |",
    "|---|---:|---:|---:|---:|",
]
for arm in ("none", "in_context", "in_context_bare"):
    row = computed_comparison[arm]
    result_table.append(
        f"| {ARM_LABELS[arm]} | {row['valid_exact_L_B']}/{row['total']} | "
        f"{row['parse_failures']} | {row['truncations']} | {row['L_A_outputs']} |"
    )

display(Markdown("\\n".join(result_table)))"""
        )
    )

    cells.append(
        nbf.v4.new_code_cell(
            """def visible_answer(raw_response: str) -> str:
    return raw_response.rsplit("</think>", 1)[-1].strip()


for arm in ("none", "in_context", "in_context_bare"):
    example = records[arm][0]
    label = ARM_LABELS[arm]
    final_answer = visible_answer(example["raw_response"])
    display(
        Markdown(
            f"### {label}: representative final answer\\n\\n"
            f"```json\\n{final_answer}\\n```\\n\\n"
            f"- Target-law match: **{example['law_match']}**\\n"
            f"- Prior-law match: **{example.get('prior_law_match', False)}**\\n"
            f"- Truncated: **{example['truncated']}**"
        )
    )"""
        )
    )

    cells.append(
        nbf.v4.new_markdown_cell(
            r"""## 7. Running a fresh response

The configured-case cells near the top support three response sources:

- `MODE = "cached"` selects a checked-in response for $L_B$, seeds 2000--2009;
- `MODE = "live_mlx"` generates one fresh Qwen3-8B response on Apple silicon;
- `PASTED_RESPONSE = "..."` scores a response copied from another model or service.

For live inference, install `python -m pip install -e ".[mac,notebook]"`, change the
top configuration cell, and rerun the notebook. Only the configured case is generated,
so a reviewer can try the system without repeating the full 130-generation study."""
        )
    )

    cells.append(
        nbf.v4.new_markdown_cell(
            r"""## 8. Interpretation and boundary of the result

Under clean, decisive controlled evidence:

- the base model recovered $L_B$;
- the guided in-context arm recovered $L_B$;
- removing explicit override guidance did not change the scientific conclusion;
- no in-context trace returned the asserted $L_A$ prior.

The supported conclusion is therefore narrow:

> An incompatible law stated in context produced no detectable bias toward that law under
> clean, directly diagnostic evidence.

This is not yet a test of persistent learning. Information supplied in context is
temporary and visible. The next experimental block introduces $L_A$ through LoRA,
checks whether the law is genuinely retrievable, and tests whether the model's original
law-induction capability survives fine-tuning."""
        )
    )

    notebook["cells"] = cells
    return notebook


def main() -> None:
    NOTEBOOK_PATH.parent.mkdir(parents=True, exist_ok=True)
    notebook = build_notebook()
    NOTEBOOK_PATH.write_text(nbf.writes(notebook))
    print(f"Wrote {NOTEBOOK_PATH}")


if __name__ == "__main__":
    main()
